# Generated by Django 3.0.4 on 2020-03-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="visibility",
            field=models.IntegerField(default=0),
        ),
    ]
