# Generated by Django 3.0.4 on 2020-05-12 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checklist", "0004_auto_20200512_1341"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Upvotes",
            new_name="Upvote",
        ),
    ]
