# Generated by Django 3.0.4 on 2020-05-18 23:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0006_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
