# Generated by Django 3.0.4 on 2020-05-19 01:53

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0007_auto_20200518_2311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="content",
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
