# Generated by Django 3.0.4 on 2020-05-27 20:49

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0010_auto_20200523_0718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="visibility",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", djrichtextfield.models.RichTextField()),
                ("priority", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checklist.Checklist",
                    ),
                ),
            ],
        ),
    ]
