# Generated by Django 3.0.4 on 2020-05-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_auto_20200527_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
