# Generated by Django 3.0.4 on 2020-06-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0012_auto_20200527_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="priority",
            field=models.PositiveIntegerField(
                choices=[(1, "Low"), (2, "Normal"), (3, "High")], default=2
            ),
        ),
    ]
