# Generated by Django 3.0.4 on 2020-06-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0014_auto_20200602_0125"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
