# Generated by Django 3.0.4 on 2020-06-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='priority',
        ),
    ]
