# Generated by Django 3.0.4 on 2021-01-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0018_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
    ]
