# Generated by Django 3.0.4 on 2021-01-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0019_auto_20210125_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
