# Generated by Django 3.0.4 on 2021-03-01 22:47

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0019_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
