# Generated by Django 3.0.4 on 2021-01-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0020_auto_20210125_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='msg',
        ),
        migrations.AddField(
            model_name='notification',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.Checklist'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.PositiveIntegerField(choices=[(1, 'upvote'), (2, 'bookmark'), (3, 'user_follow')], default=1),
        ),
    ]
