# Generated by Django 3.0.4 on 2021-01-26 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0021_auto_20210125_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.PositiveIntegerField(choices=[(1, 'upvote'), (2, 'user_follow'), (3, 'checklist_follow')], default=1),
        ),
        migrations.CreateModel(
            name='FollowChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUserFC', to=settings.AUTH_USER_MODEL)),
                ('toChecklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toChecklist', to='checklist.Checklist')),
            ],
        ),
    ]
