# Generated by Django 3.0.4 on 2021-01-26 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0022_auto_20210126_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='toUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toUserNotif', to=settings.AUTH_USER_MODEL),
        ),
    ]
